---
Timeout: 10
SteamApiKey:  "<Steam API Key>"
SteamApi: "https://api.steampowered.com"
SteamUser: "ISteamUser"
SteamApiVersion: "V001"
Dota2Match: "IDOTA2Match_570"
Dota2Econ: "IEconDOTA2_570"
Dota2CDN: "http://cdn.dota2.com/apps/dota2/images"
Dota2ApiVersion: "V001"
